name: habit_tracker
description: A comprehensive habit tracking app with Firebase integration, progress visualization, and motivational quotes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # HTTP & API
  http: ^1.1.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Charts
  fl_chart: ^0.65.0
  
  # Utils
  uuid: ^4.2.1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
