// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9fZq_-WJ58Mw2qVSJt9aoRx9osAk7fE',
    appId: '1:454704991884:web:8e790a51b9ac701fbcb5a9',
    messagingSenderId: '454704991884',
    projectId: 'habit-602f2',
    authDomain: 'habit-602f2.firebaseapp.com',
    storageBucket: 'habit-602f2.firebasestorage.app',
    measurementId: 'G-E1TGLH051L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDME9mmSXIqy79INsFeUTuoEpDA7KlRpUA',
    appId: '1:454704991884:android:a9b8c9d5021159a6bcb5a9',
    messagingSenderId: '454704991884',
    projectId: 'habit-602f2',
    storageBucket: 'habit-602f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJWSEUjRzIwE855LaCCCpd1akyCcvkqRY',
    appId: '1:454704991884:ios:64d80dd456f89875bcb5a9',
    messagingSenderId: '454704991884',
    projectId: 'habit-602f2',
    storageBucket: 'habit-602f2.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJWSEUjRzIwE855LaCCCpd1akyCcvkqRY',
    appId: '1:454704991884:ios:64d80dd456f89875bcb5a9',
    messagingSenderId: '454704991884',
    projectId: 'habit-602f2',
    storageBucket: 'habit-602f2.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE9fZq_-WJ58Mw2qVSJt9aoRx9osAk7fE',
    appId: '1:454704991884:web:793125552f6d6f62bcb5a9',
    messagingSenderId: '454704991884',
    projectId: 'habit-602f2',
    authDomain: 'habit-602f2.firebaseapp.com',
    storageBucket: 'habit-602f2.firebasestorage.app',
    measurementId: 'G-W9CRWHT1Y8',
  );
}
